# Generated by Django 2.1.7 on 2019-03-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
                ('Family', models.CharField(max_length=300)),
                ('Email', models.EmailField(default='khashayar.boush@programmer.net', max_length=254)),
                ('Phone', models.IntegerField()),
            ],
        ),
    ]
